test_that("MorphyNet source relations and scoped identities survive import", {
  path <- system.file("extdata", "morphynet-example", "eng.derivational.example.tsv",
    package = "ldfreq", mustWork = TRUE)
  x <- morphynet_read_derivations(path, "en", "v1 excerpt")
  d <- x$relations
  expect_equal(nrow(d), 9L)
  expect_identical(d$source_line, 1:9)
  expect_equal(anyDuplicated(d$relation_id), 0L)
  expect_identical(x$resource$source_sha256, digest::digest(file = path, algo = "sha256"))
  expect_identical(x$resource$data_license, "CC BY-SA 3.0")
  expect_identical(d$source_pos[d$target_word == "teacher"], "N")
  r <- d[d$target_word == "reusability", ]
  expect_identical(r$source_word, c("reuse", "reusable", "usability"))
  expect_identical(r$morpheme, c("ability", "ity", "re"))
  expect_identical(r$affix_position, c("suffix", "suffix", "prefix"))
  expect_false("teachers" %in% d$target_word)
  tmp <- tempfile(); out <- tempfile(); on.exit(unlink(c(tmp, out)))
  file.copy(path, tmp)
  expect_identical(morphynet_read_derivations(tmp, "en", "v1 excerpt"), x)
  saveRDS(x, out)
  expect_identical(readRDS(out), x)
  writeLines(c("base word\tNA\tU\tJ\tun\tprefix", "base word\tNA\tU\tJ\tun\tprefix"), tmp)
  duplicate <- morphynet_read_derivations(tmp, "en", "authored schema test")
  expect_identical(duplicate$relations$target_word, rep("NA", 2L))
  expect_identical(duplicate$relations$source_word, rep("base word", 2L))
  expect_equal(nrow(duplicate$relations), 2L)
  expect_equal(anyDuplicated(duplicate$relations$relation_id), 0L)
  writeBin(c(as.raw(c(239, 187, 191)), charToRaw("base\ttarget\tU\tN\tx\tsuffix")), tmp)
  bom <- morphynet_read_derivations(tmp, "en", "BOM and no final newline")
  expect_identical(bom$relations$source_word, "base")
  expect_identical(bom$relations$source_pos, "U")
})

test_that("malformed or truncated relations fail instead of changing columns", {
  p <- tempfile(); on.exit(unlink(p))
  expect_error(morphynet_read_derivations(p, "en", "v1"), "local")
  expect_error(morphynet_read_derivations(tempdir(), "en", "v1"), "local")
  writeLines(character(), p)
  expect_error(morphynet_read_derivations(p, "en", "v1"), "empty")
  for (line in c("a\tb\tV", "a\tb\tV\tN\ter\tsuffix\t", "a\tb\tV\tN\ter\t", "")) {
    writeLines(line, p)
    expect_error(morphynet_read_derivations(p, "en", "v1"), "six")
  }
  writeLines("a\tb\tV\tN\t \tsuffix", p)
  expect_error(morphynet_read_derivations(p, "en", "v1"), "whitespace")
  writeLines("a\tb\tV\tN\ter\troot", p)
  expect_error(morphynet_read_derivations(p, "en", "v1"), "prefix or suffix")
  writeLines(rep("a\tb\tV\tN\ter\tsuffix", 2), p)
  expect_error(morphynet_read_derivations(p, "en", "v1", max_rows = 1), "exceed")
  expect_equal(nrow(morphynet_read_derivations(p, "en", "v1", max_rows = 2)$relations), 2L)
  expect_error(morphynet_read_derivations(p, "\u3000", "v1"), "blank")
  expect_error(morphynet_read_derivations(p, "en", " "), "blank")
  for (bad in list(0, -1, 1.5, NA_real_, Inf, "2", .Machine$integer.max))
    expect_error(morphynet_read_derivations(p, "en", "v1", max_rows = bad))
  writeBin(c(charToRaw("a\tb\tV\tN\t"), as.raw(255), charToRaw("\tsuffix\n")), p)
  expect_error(morphynet_read_derivations(p, "en", "v1"), "UTF-8")
  writeBin(c(charToRaw("a\tb\tV\tN\ter\tsuffix"), as.raw(0), charToRaw("hidden\n")), p)
  expect_error(morphynet_read_derivations(p, "en", "v1"), "Cannot read")
})

test_that("KWIC decisions retain alternatives and distinguish repeated occurrences", {
  skip_if_not_installed("quanteda")
  env <- new.env(parent = asNamespace("ldfreq"))
  sys.source(system.file("examples", "morphynet-relations.R", package = "ldfreq",
    mustWork = TRUE), env)
  x <- env$morphynet_example
  expect_equal(nrow(x$initial$occurrences), 5L)
  expect_identical(x$initial$occurrences$candidate_count, c(1L, 1L, 3L, 3L, 0L))
  expect_equal(sum(x$reviewed$occurrences$status == "selected"), 1L)
  expect_equal(sum(x$reviewed$occurrences$status == "unresolved"), 1L)
  expect_equal(sum(x$reviewed$occurrences$status == "no_candidates"), 1L)
  expect_identical(x$selected$source_word, "reusable")
  expect_identical(x$selected$morpheme, "ity")
  expect_identical(x$reviewed$candidates, x$initial$candidates)
  expect_equal(nrow(x$annotations$segments), 5L)
  expect_equal(nrow(x$annotations$tokens), 17L)
  p <- tempfile(); on.exit(unlink(p)); saveRDS(x, p); restored <- readRDS(p)
  replay <- lexdiv_ambiguity_review(restored$annotations, restored$targets,
    restored$candidates, restored$resource, decisions = restored$reviewed$decisions)
  expect_identical(replay, x$reviewed)
  changed <- x$resource; changed$resource_version <- "other snapshot"
  expect_error(lexdiv_ambiguity_review(x$annotations, x$targets, x$candidates,
    changed, decisions = x$reviewed$decisions), "review_id differs")
})
